#!/bin/bash

# check if binary is already linked, if so remove it
ttt_exists=/usr/local/bin/ttt
if [ -f "$ttt_exists" ]; then
    sudo rm -rf /usr/local/bin/ttt /usr/local/lib/tic-tac-toe
fi

cargo build --release

sudo cp target/release/tic-tac-toe /usr/local/lib
sudo ln -s /usr/local/lib/tic-tac-toe /usr/local/bin/ttt